"""new fields in user model

Revision ID: 621cea6ee525
Revises: 053a8f639780
Create Date: 2020-07-06 11:14:23.096892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621cea6ee525'
down_revision = '053a8f639780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
